services:
  - type: web
    name: bsu-api
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    buildFilter:
      paths:
        - src/**
        - data/**
        - bsm-config/**
        - package.json
        - package-lock.json
        - render.yaml
