name = "bsm-worker"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = false
route = "example.com/*"
zone_id = "YOUR_ZONE_ID"

[build]
command = "npm run build"

[env.production]
route = "example.com/*"
zone_id = "YOUR_ZONE_ID"
